return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = "1000",
		require("catppuccin").setup({
			flavour = "auto",
			background = { -- :h background
				light = "latte",
				dark = "mocha",
			},
			transparent_background = false,
			show_end_of_buffer = true,
			term_colors = false,
			dim_inactive = { enabled = false, shade = "dark", percentage = 0.15 },
			no_italic = true,
			no_bold = false,
			no_underline = false,
			styles = {
				comments = {},
				conditionals = {},
				loops = {},
				functions = { "bold" },
				keywords = {},
				strings = {},
				variables = { "underline" },
				numbers = {},
				booleans = {},
				properties = {},
				types = {},
				operators = {},
			},
			color_overrides = {},
			custom_highlights = {},
			default_integrations = true,
			integrations = {
				alpha = true,
				cmp = true,
				gitsigns = true,
				nvimtree = true,
				treesitter = true,
				notify = false,
				mini = { enabled = true, indentscope_color = "" },
			},
		}),
	},
}
